import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/page'
import Footer from '@/components/Footer/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Transport-management-system',
  description: 'Generated by Joseph',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className='container'>
      <Navbar/>
      {children}
      <Footer/>
      </div>
      </body>
    </html>
  )
}
